### ISSUE TITLE
Migrate to native Android and GWT

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/vograbulary#40]
Libgdx is frustrating and the new release was difficult to set up.

PlayN has limited documentation and no support for native fields.

Maybe it's time to try native Android and GWT to support my two primary targets. Another option is to rewrite in Python with QPython on Android and Skulpt in the browser.

There will be several smaller issues to make up this big transition, as well as a few miscellaneous tasks.

* [x] #41 Create a native branch and minimal Android project
* [x] #42 Create minimal GWT project
* [x] #43 Drag an arrow left and right
* [x] #44 Use model classes for Russian Dolls
* [x] #45 Create separate screens
* [x] #47 Migrate Ultraghost to native platforms
* [x] #48 Student names on native platforms
* [x] option for minimum number of letters in Ultraghost
* [x] option for vocabulary size of computer student
* [x] enter key in Ultraghost
* [x] enter key on physical keyboard in response
* [x] enter key in solution after computer student challenge
* [ ] monospace fonts for solution, response, and hint
* [ ] bigger fonts

I created a [sample project][webandnative] to try out the techniques for targeting the native platforms, as well as to document all the alternative platforms I've tried with this project.

[webandnative]: https://github.com/donkirkby/webandnative
